### PR TITLE
Make header parse next extension header type

### PR DESCRIPTION
**Pull request by yt8956gh**
Make header parse next extension header type
- Add NextExtensionHeaderType field in header
- Parse NextExtensionHeaderType in UnmarshalBinary if E flag is set
- Set some method to access NextExtensionHeaderType aside for the future

### CODE REVIEW

**Comment by wmnsk** [comment]
Great, thank you!

My plan is to add `ExtensionHeader` struct and embed it as `ExtensionHeaders []*ExtensionHeader` in `Header` explicitly(separate from `Payload`), but since it’ll take some more time and considerations and it seems you want this soon, I’m approving and tagging the these changes as they are for now. Please note that the implementation will change in the near future as described above (of course with another tag).

**Comment by wmnsk** [comment]
@yt8956gh Tagged as v0.7.27. Enjoy parsing!

**Comment by yt8956gh** [comment]
@wmnsk , Thank you
I recently added a parser dumping extension header data into a struct similar to what you want.
The code is [here](https://github.com/free5gc/n3iwf/blob/ba2af2ab7924f858f5904d7323804c58add3de4e/gtp/service/message.go#L87)
Maybe this can help you 😉

**Comment by wmnsk** [comment]
Cool, it surely helps. Thank you 👍

**Pull request merged**
