### PR TITLE
Expose separatley Listen and Server on gtpv2.conn 

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

This PR exposes `conn.Listen` and `conn.Serv` so client can be initialized in two steps
1- create listener
2- run the serve method

The reason to expose that is `ListenAndServe` function is normally run on a go routine in parallel. If we use the client too quick, the listener may not be initialized yet and it will panic.  Having the `Listen` and `Serve` method exposed allows us to separate the initialization of the client from the execution of the gtp server.

This PR also modifies the `setup` function at `conn_test.go` to use this two step process instead of a 1 second wait. 

`ListenAndServe` can still be used as it was (with the panic issue in case of using the client too soon after init)

### CODE REVIEW

**Comment by wmnsk** [comment]
Give me some time for a review: probably one week or so.

**Comment by uri200** [comment]
no rush

**Review by wmnsk — APPROVED** [review]
Tested and worked locally. Thanks, and sorry leaving for a long time.

**Comment by uri200** [comment]
No problem

Will rebase soon with https://github.com/magma/magma

Thanks!

**Comment by uri200** [comment]
Hey @wmnsk will you tag a version anytime soon which includes this change?

**Comment by wmnsk** [comment]
Tagged with v0.7.16 :tada: 
https://github.com/wmnsk/go-gtp/releases/tag/v0.7.16

**Pull request merged**
